#!/usr/bin/env python3
"""One-off generator for lib/sp500-tsx60-tickers.ts.

Re-run this script a few times a year when S&P 500 / TSX 60 constituents
change (see docs/superpowers/specs/2026-09-04-nl-stock-screener-design.md,
"Non-goals" — this list is static, not auto-refreshed). Not part of the
app runtime.

Usage: python3 scripts/generate-tickers.py
"""
import json
import re
import urllib.request

HEADERS = {"User-Agent": "intrinsic-ticker-sync/1.0"}


def fetch_wikitext(page_title: str) -> str:
    url = (
        "https://en.wikipedia.org/w/api.php?action=parse&page="
        + page_title
        + "&prop=wikitext&format=json&formatversion=2"
    )
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.load(resp)
    return data["parse"]["wikitext"]


def parse_sp500(wikitext: str) -> list[str]:
    # The Symbol column on "List of S&P 500 companies" uses an
    # exchange-specific template call per row, e.g. {{NyseSymbol|MMM}} or
    # {{NasdaqSymbol|ADBE}} (as of 2026-09, Wikipedia no longer uses the
    # older {{ticker|SYMBOL}} template).
    return sorted(set(re.findall(r"\{\{\w*Symbol\|([A-Z.\-]+)\}\}", wikitext)))


def parse_tsx60(wikitext: str) -> list[str]:
    # The "S&P/TSX 60" wikitable's Symbol column uses a {{TSX link|SYMBOL}}
    # template call per row (as of 2026-09, Wikipedia no longer uses bare
    # "| SYMBOL ||" row cells).
    return sorted(set(re.findall(r"\{\{TSX link\|([A-Z.]+)\}\}", wikitext)))


def to_yahoo_symbol_us(sym: str) -> str:
    # BRK.B -> BRK-B (matches lib/symbol-normalize.ts convention)
    return sym.replace(".", "-")


def to_yahoo_symbol_tsx(sym: str) -> str:
    base = sym[:-3] if sym.endswith(".TO") else sym
    return f"{base.replace('.', '-')}.TO"


def main() -> None:
    sp500_raw = parse_sp500(fetch_wikitext("List_of_S%26P_500_companies"))
    tsx60_raw = parse_tsx60(fetch_wikitext("S%26P/TSX_60"))

    sp500 = [(to_yahoo_symbol_us(s), "US") for s in sp500_raw]
    tsx60 = [(to_yahoo_symbol_tsx(s), "TSX") for s in tsx60_raw]

    entries = sorted(set(sp500 + tsx60))

    if len(entries) < 400:
        raise SystemExit(
            f"Only parsed {len(entries)} tickers — Wikipedia table format "
            "likely changed. Inspect parse_sp500/parse_tsx60 before "
            "committing this output."
        )

    lines = [
        "// Auto-generated by scripts/generate-tickers.py — do not hand-edit.",
        "// Re-run the script to refresh when index constituents change.",
        "",
        'export type ScreenerExchange = "US" | "TSX";',
        "",
        "export type ScreenerTicker = {",
        "  symbol: string;",
        "  exchange: ScreenerExchange;",
        "};",
        "",
        "export const SCREENER_TICKERS: ScreenerTicker[] = [",
    ]
    for symbol, exchange in entries:
        lines.append(f'  {{ symbol: "{symbol}", exchange: "{exchange}" }},')
    lines.append("];")
    lines.append("")

    with open("lib/sp500-tsx60-tickers.ts", "w") as f:
        f.write("\n".join(lines))

    print(f"Wrote {len(entries)} tickers to lib/sp500-tsx60-tickers.ts")
    print(f"  S&P 500: {len(sp500)}, TSX 60: {len(tsx60)}")


if __name__ == "__main__":
    main()
